#!/bin/sh
# Native git hook, versioned in .githooks/ and wired via `core.hooksPath`
# (see scripts/setup-git-hooks.js, run automatically by `bun install`).
# Single entry point for every deterministic guardrail on staged files (#32):
# SPDX headers, Biome, and the typecheck, all via scripts/check.js -- bun end
# to end, no Node dependency (the previous `node scripts/...` call here was
# the one remaining Node dependency in an otherwise all-bun toolchain).

set -e

bun scripts/check.js --staged
